version: '3.8'

services:
  web:
    build: ./
    # command: python manage.py runserver 0.0.0.0:8000
    # command: > 
    #   sh -c "
    #   python manage.py makemigrations
    #   && python manage.py migrate --noinput
    #   && python manage.py collectstatic --noinput 
    #   && python manage.py shell -c 'from django.contrib.auth.models import User; User.objects.create_superuser("${ADMIN_USERNAME}", f"${ADMIN_EMAIL}", f"${ADMIN_PASSWORD}")'
    #   && python manage.py shell < createadmin.py --noinput
    #   && python manage.py runserver 0.0.0.0:8000
    #   "
    command:
    - /bin/sh
    - -c
    - |
       python manage.py makemigrations
       python manage.py migrate --noinput
       python manage.py collectstatic --noinput 
       python manage.py shell -c "from django.contrib.auth.models import User; User.objects.create_superuser('${ADMIN_USERNAME}', '${ADMIN_EMAIL}', '${ADMIN_PASSWORD}')"
       python manage.py shell < createadmin.py 
       python manage.py runserver 0.0.0.0:8000

    volumes:
      - .:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./default.env
    depends_on:
      - db
    networks:
      - backend
  db:
    image: postgres:latest
    expose: 
      - 5432
    networks:
      - backend
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${SQL_USER}
      - POSTGRES_PASSWORD=${SQL_PASSWORD}
      - POSTGRES_DB=${SQL_DATABASE}

volumes:
  postgres_data:

networks:
  backend:
    driver: bridge