# Generated by Django 4.1.1 on 2022-10-06 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Description',
            fields=[
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.group')),
                ('current_stage', models.CharField(max_length=128)),
                ('version', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=128)),
                ('model_author', models.CharField(blank=True, max_length=128, null=True)),
                ('model_url', models.CharField(max_length=128)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
